# Cloudflare Pages Configuration
# https://developers.cloudflare.com/pages/

name = "srwa-frontend"
compatibility_date = "2025-10-18"

# Build configuration
[build]
command = "npm run build"
cwd = "frontend"
watch_dirs = ["frontend/src"]

# Upload configuration
[build.upload]
dir = "frontend/dist"
format = "service-worker"

# Environment variables (configure these in Cloudflare Dashboard)
# Production environment
[env.production]
# VITE_SOLANA_NETWORK = "mainnet-beta"
# VITE_SOLANA_RPC_URL_MAINNET_BETA = "your-rpc-url"

# Preview environment
[env.preview]
# VITE_SOLANA_NETWORK = "devnet"
# VITE_SOLANA_RPC_URL_DEVNET = "https://api.devnet.solana.com"
