[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
srwa_factory = "G2TVaEY5pxLZbdBUq28Q7ZPGxQaxTxZzaSRTAEMh3z2A"
srwa_controller = "HnPCaGFDW2Y7B9J1q8ZHnwKNZZ9ZhXfcnAGcEVK3Y6nA"
identity_claims = "AuUzmKAAVyvR6NvDdd56SDjXHSE8dUePEnC5moECw9mE"
compliance_modules = "GD3ArP1GPKN9sWYPxiPia2i3iAKKsnbXxpcoB1gQK5D"
offering_pool = "4D54H4NBA9Q7WtsAy2yaFs9BjEdT8DcdmXekKsf7n6KP"
yield_adapter = "qSDUx7334aHWP44csqnJV61AmzC9vNmUKusJX4GQnor"
valuation_oracle = "C4sJ1phqCh2MxFJJqVHZuddXbp6hWfvz29N4CkscPpaW"
cashflow_engine = "4ySjU9NzSwg457oxWCVgaH3fqqrhh7iDQco7Db1Zq4Di"

[programs.devnet]
srwa_factory = "G2TVaEY5pxLZbdBUq28Q7ZPGxQaxTxZzaSRTAEMh3z2A"
srwa_controller = "HnPCaGFDW2Y7B9J1q8ZHnwKNZZ9ZhXfcnAGcEVK3Y6nA"
identity_claims = "AuUzmKAAVyvR6NvDdd56SDjXHSE8dUePEnC5moECw9mE"
compliance_modules = "GD3ArP1GPKN9sWYPxiPia2i3iAKKsnbXxpcoB1gQK5D"
offering_pool = "4D54H4NBA9Q7WtsAy2yaFs9BjEdT8DcdmXekKsf7n6KP"
yield_adapter = "qSDUx7334aHWP44csqnJV61AmzC9vNmUKusJX4GQnor"
valuation_oracle = "C4sJ1phqCh2MxFJJqVHZuddXbp6hWfvz29N4CkscPpaW"
cashflow_engine = "4ySjU9NzSwg457oxWCVgaH3fqqrhh7iDQco7Db1Zq4Di"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/temp-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
